remote-week1: initial commit
jonathanwu906/remote-assignments pull request #1
Opened 2023-02-16 08:50 UTC by jonathanwu906

Elastic IP: 52.194.120.101
DB Host: database-1.cl0em6x5mxvq.ap-northeast-1.rds.amazonaws.com
Changes: 

- add readme
- intial express.js
- create health check.api

2023-02-19 08:03 UTC, addie-tyc approved these changes
LGTM

2023-02-26 15:46 UTC, jonathanwu906 commented
增加backup.sql, app.js, requestSync.js, requestAsync.js，
1. async functions 的執行時間較少
2. 同時有好幾件事情要執行時，執行好的可以先回傳，並不需要等到前面順序的執行好回傳完畢之後再回傳
3. async 能使用promise也能避免callback hell，並且寫起來和sync function類似
4. 無

![messageImage_1677426117005](https://user-images.githubusercontent.com/61775916/221420689-9c0d4517-c7da-4518-863a-9de7b37383e1.jpg)

2023-02-26 15:54 UTC, addie-tyc reviewed
看起來還可以（我還沒測試），除了 app.js hardcode 的 id 和 `req.body.id` 之外乍看沒什麼問題

2023-02-26 15:54 UTC, addie-tyc commented on app.js
> +  }
id 是 query parameter 呦，要怎麼拿呢？

2023-03-01 12:17 UTC, addie-tyc requested changes

2023-03-01 12:17 UTC, addie-tyc commented on index.js
> +  const get_date = new Date().toUTCString();
request 帶進來的 id 在什麼位置？
request date 應該在哪裡取得？
再幫我確認 API 文件～

2023-03-01 12:17 UTC, addie-tyc commented on index.js
> +            "date": request_date,
同上

2023-03-01 12:17 UTC, addie-tyc commented on index.js
> +  if (passwordValidation(userData.password) && userData.email.includes("@")) {
email 的檢驗邏輯要再修正一下，name 也需要檢驗呦

2023-03-01 12:20 UTC, addie-tyc commented
<img width="1017" alt="截圖 2023-03-01 20 19 27" src="https://user-images.githubusercontent.com/65952631/222137542-599dfdec-8a46-492b-93fc-ac206f0a09a0.png">
如果 client 發生錯誤導致沒有正常的結果，也不可以把給開發者看的 error 傳回來喔！
<img width="1014" alt="截圖 2023-03-01 20 18 22" src="https://user-images.githubusercontent.com/65952631/222137551-477f99b1-9193-4422-b67c-9909628a2e5d.png">
應該通過的測資沒過

2023-03-04 18:20 UTC, addie-tyc approved these changes
LGTM. A1 的話可以再多著墨一些

2023-03-05 16:01 UTC, addie-tyc approved these changes
LGTM

2023-03-05 16:01 UTC, addie-tyc commented on frontend/src/App.js
> +      console.log(response.data.data.user);
通常 await 不會和 then 一起用，可以想想看/查查看為什麼～

2023-03-05 16:03 UTC, jonathanwu906 commented on frontend/src/App.js
> +      console.log(response.data.data.user);
好，謝謝Addie的建議！

2023-03-06 00:46 UTC, jonathanwu906 commented on frontend/src/App.js
> +      console.log(response.data.data.user);
![image](https://user-images.githubusercontent.com/61775916/222996238-43f145f3-f9bf-469c-a32c-80c5e9f45c9e.png)

我改成這樣！

2024-06-18 02:23 UTC, closed without merging